/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Call as PrismaCall } from "@prisma/client";

export class CallServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.CallCountArgs, "select">): Promise<number> {
    return this.prisma.call.count(args);
  }

  async calls(args: Prisma.CallFindManyArgs): Promise<PrismaCall[]> {
    return this.prisma.call.findMany(args);
  }
  async call(args: Prisma.CallFindUniqueArgs): Promise<PrismaCall | null> {
    return this.prisma.call.findUnique(args);
  }
  async createCall(args: Prisma.CallCreateArgs): Promise<PrismaCall> {
    return this.prisma.call.create(args);
  }
  async updateCall(args: Prisma.CallUpdateArgs): Promise<PrismaCall> {
    return this.prisma.call.update(args);
  }
  async deleteCall(args: Prisma.CallDeleteArgs): Promise<PrismaCall> {
    return this.prisma.call.delete(args);
  }
}
